export default {
    welcomeScreenWallpaper : `https://i.pinimg.com/736x/16/6a/4e/166a4e6fb817ded1f4002a27581d339c.jpg`,
    backbtn : require(`./img/back.png`),
    googlebtn : require(`./img/googleBtn.png`),
    facebookbtn : require('./img/facebookBtn.png'),
    applebtn : require(`./img/appleBtn.png`),
    eyeIcon : require(`./img/eyeIcon.png`),
    homeIcon : require(`./img/home.png`),
    searchIcon : require(`./img/search.png`),
    planIcon : require(`./img/plan.png`),
    guideIcon : require(`./img/guide.png`),
    homeActiveIcon : require(`./img/activeHome.png`),
    searchActiveIcon : require(`./img/activeSearch.png`),
    planActiveIcon : require(`./img/activePlan.png`),
    guideActiveIcon : require(`./img/activeGuide.png`),
}